# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20180413_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default=None, upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
